### PR TITLE
Remove Group object entirely

### PR DESCRIPTION
**Pull request by dotsdl**
As ``datreant`` has evolved, the functionality originally provided by the ``Group`` object has been largely superseded by the ``Bundle`` combined with ``datreant.core.discover``. The ``Group`` object was always susceptible to breakage due to its member locations possibly becoming stale over time as ``Treant``s are moved. This also helps to unify the concept of a ``Treant`` such that the library provides one, and only one, ``Treant`` class to use.

I've removed all traces of ``Group``s in this PR.

### CODE REVIEW

**Comment by kain88-de** [comment]
How is this decreasing coverage?

**Comment by kain88-de** [comment]
Can you figure out what code paths aren't tested anymore now?

**Comment by dotsdl** [comment]
@kain88-de hmmm...probably because the size of the library dropped and so did the number of tests, so overall percentage covered ended up being less in the end.

**Comment by dotsdl** [comment]
There's a lot of areas where we can increase coverage, so I'm not too worried about these drops for now. Agree it's something that should be worked on, though.

**Pull request merged**
