### PR TITLE
AggTags tests for set behavior and getitem (Issue #46)

### PR DESCRIPTION
**Pull request by sseyler**
There should now be complete test coverage for `AggTags.__getitem__()` and `AggTags.fuzzy()` (in `test_tags_getitem()` and `test_tags_fuzzy()`) . The remaining tests that must be written are for testing `AggTags` set behavior in `test_tags_set_behavior()`.

### CODE REVIEW

**Comment by sseyler** [comment]
What are the set operators that have an "r" preceding their name (`__ror__`, `__rxor__`, etc.)? As written, they're identical to the implementations without the "r".

**Comment by sseyler** [comment]
**Note**: For python2.7, accessing an error message with something like `pytest.raises(TypeError) as e:` requires using `e.value.message`. But in python3, one must use `e.value`. I commented out these assertions for the time being to get python2.7 and python3 checks to pass until I'm aware of a better solution.

**Comment by dotsdl** [comment]
@sseyler I wouldn't worry about testing the exception message; testing that it raises the proper exception (in this case, ``TypeError``) is sufficient. That is what a user would have to catch, anyway, to do anything with it.

**Comment by sseyler** [comment]
#DatCodeCoverage

**Comment by dotsdl** [comment]
Looks great! Thanks @sseyler! Merging.

**Pull request merged**
