### PR TITLE
Rebase of #142 (None category)

### PR DESCRIPTION
**Pull request by dotsdl**
Supercedes #142. Performed a rebase against current `develop`. Not sure why @richardjgowers commit seems lost(?!).

Merge commit needs to credit @richardjgowers for this enhancement.

### CODE REVIEW

**Comment by dotsdl** [comment]
Ah, I know what happened. I absentmindedly did a `git commit` instead of `git rebase --continue`. :/

**Comment by kain88-de** [comment]
You can change the author with interactive rebase

**Comment by dotsdl** [comment]
@richardjgowers I changed the author of the commit to you, since these are your additions. Sorry for the foul-up on my part.

**Comment by richardjgowers** [comment]
Yeah this looks good

**Comment by dotsdl** [comment]
Awesome! Merging!

**Pull request merged**
