### PR TITLE
Coverage for core.trees

### PR DESCRIPTION
**Pull request by richardjgowers**

### CODE REVIEW

**Comment by dotsdl** [comment]
@richardjgowers you are on a roll! Looks like we've got some Travis failures; ping me when you're ready for review.

**Comment by richardjgowers** [comment]
Might be using this for a new project so wanted to shake it down :P

I think draw is giving a different order in py3...

**Comment by dotsdl** [comment]
Excellent, happy to have you hammering on it. I'm back to hardcore development over the next few weeks (been putting out science fires), so also wanting to get `datreant.core` in the place we'd like it to be.

**Comment by richardjgowers** [comment]
@dotsdl ping

**Comment by dotsdl** [comment]
@richardjgowers thanks! Sorry for the delay; merging!

**Pull request merged**
